version: '3.3'

services:
  ldap:
    image: xsystems/ldap:1.0.0
    environment:
      - LDAP_SCHEMAS
      - LDAP_SUFFIX
      - LDAP_ROOTDN
      - LDAP_ROOTPW
      - LDAP_MEMBEROF_ENABLED
      - LDAP_TLS_ENABLED
      - LDAP_TLS_PATH
    volumes:
      - letsencrypt:/etc/letsencrypt
    networks:
      - xsystems-network
  client-web:
    image: xsystems/windhappers-client-web
    networks:
      - xsystems-network
  proxy:
    build:
      context: contexts/proxy
    environment:
      - PROXY_DOMAIN
      - PROXY_EMAIL
      - PROXY_CERTIFICATE_RENEWAL_INTERVAL
      - PROXY_STAGING_DISABLED
    volumes:
      - /dev/log:/dev/log
      - letsencrypt:/etc/letsencrypt
    networks:
      - xsystems-network
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "9090:9090"

volumes:
  letsencrypt:
    driver: local

networks:
  xsystems-network:
