version: '3.2'

services:
  client-web:
    image: xsystems/windhappers-client-web
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: '128M'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    networks:
      - windhappers-network

  proxy:
    image: xsystems/windhappers-proxy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: '64M'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    env_file: windhappers-stack.env
    environment:
      - PROXY_STAGING_DISABLED=${PROXY_STAGING_DISABLED}
    volumes:
      - /dev/log:/dev/log
      - windhappers-letsencrypt:/etc/letsencrypt
    networks:
      - windhappers-network
    ports:
      - "80:80"
      - "443:443"


volumes:
  windhappers-letsencrypt:
    external: true


networks:
  windhappers-network:
