version: '3.5'

services:
  jenkins:
    image: jenkins/jenkins:alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s      
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 60s
    user: "root"
    volumes:
      - xsystems-jenkins:/var/jenkins_home
    networks:
      - xsystems
    ports:
      - "80:8080"

volumes:
  xsystems-jenkins:
    external: true

networks:
  xsystems:
    external: true
